---
galaxy_info:
  author: 'Chris Hambridge'
  description: 'Collect OCP usage data to send to Insights'
  company: 'Red Hat, Inc.'
  issue_tracker_url: 'https://github.com/project-koku/korekuta/issues'
  license: 'AGPLv3'
  min_ansible_version: 2.4
  platforms:
    - name: RHEL
      versions:
        - all
  galaxy_tags: ['hccm', 'cost-management', 'openshift', 'kubernetes', 'redhat']
dependencies: []
